import type { NextPage } from 'next';
import Link from 'next/link';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
// import SelfieHooks from '../src/components/SelfieHooks';

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Link href="/selfie" passHref>
                    <button style={{ padding: '5px 10px 5px 10px' }}>
                        Camera test
                    </button>
                </Link>
            </main>
        </div>
    );
};

export default Home;
